# Generated by Django 3.1.6 on 2024-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240629_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_articles',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
